#!/bin/sh

# cleanup 

rm -rf obj_dir
rm -f RayTracingUnit.vcd

#run verilator to translate Verilog into C++
verilator -Wall --cc --trace RayTracingUnit.sv --exe RayTracingUnit_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VRayTracingUnit.mk VRayTracingUnit

# run executable simulation
obj_dir/VRayTracingUnit

python3 convert.py

echo "Shell script executed successfully."