#!/bin/sh

# cleanup 

rm -rf obj_dir
rm -f RayGenerator.vcd

#run verilator to translate Verilog into C++
verilator -Wall --cc --trace RayGenerator.sv --exe RayGenerator_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VRayGenerator.mk VRayGenerator

# run executable simulation
obj_dir/VRayGenerator