#!/bin/sh

# cleanup 

rm -rf obj_dir
rm -f RayGeneratorOld.vcd

#run verilator to translate Verilog into C++
verilator -Wall --cc --trace RayGeneratorOld.sv --exe RayGeneratorOld_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VRayGeneratorOld.mk VRayGeneratorOld

# run executable simulation
obj_dir/VRayGeneratorOld

