#!/bin/sh

# cleanup 

rm -rf obj_dir
rm -f RayTracerSimple.vcd

#run verilator to translate Verilog into C++
verilator -Wall --cc --trace RayTracerSimple.sv --exe RayTracerSimple_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f VRayTracerSimple.mk VRayTracerSimple

# run executable simulation
obj_dir/VRayTracerSimple